# NACE Rev.2 Classification Names for Latvia
# Official NACE 2-digit division names in Latvian

NACE_DIVISIONS = {
    "01": "Augkopība un lopkopība, medniecība un saistītas palīgdarbības",
    "02": "Mežsaimniecība un mežizstrāde",
    "03": "Zvejniecība un akvakultūra",
    "05": "Ogļu un lignīta ieguve",
    "06": "Jēlnaftas un dabasgāzes ieguve",
    "07": "Metālrūdu ieguve",
    "08": "Pārējā ieguves rūpniecība",
    "09": "Ieguves rūpniecību palīgdarbības",
    "10": "Pārtikas produktu ražošana",
    "11": "Dzērienu ražošana",
    "12": "Tabakas izstrādājumu ražošana",
    "13": "Tekstilizstrādājumu ražošana",
    "14": "Apģērbu ražošana",
    "15": "Ādas un ādas izstrādājumu ražošana",
    "16": "Koksnes un koka izstrādājumu ražošana",
    "17": "Papīra un papīra izstrādājumu ražošana",
    "18": "Poligrāfija un ierakstu reproducēšana",
    "19": "Koksa un naftas produktu ražošana",
    "20": "Ķīmisko vielu un produktu ražošana",
    "21": "Farmaceitisko preparātu ražošana",
    "22": "Gumijas un plastmasas izstrādājumu ražošana",
    "23": "Nemetālisko minerālu izstrādājumu ražošana",
    "24": "Metālu ražošana",
    "25": "Gatavo metālizstrādājumu ražošana",
    "26": "Datoru, elektronisko un optisko iekārtu ražošana",
    "27": "Elektrisko iekārtu ražošana",
    "28": "Citur neklasificētu iekārtu un mehānismu ražošana",
    "29": "Automobiļu un piekabju ražošana",
    "30": "Citu transportlīdzekļu ražošana",
    "31": "Mēbeļu ražošana",
    "32": "Cita veida ražošana",
    "33": "Iekārtu un ierīču remonts un uzstādīšana",
    "35": "Elektroenerģija, gāzes apgāde, siltumapgāde un gaisa kondicionēšana",
    "36": "Ūdens ieguve, attīrīšana un apgāde",
    "37": "Notekūdeņu savākšana un attīrīšana",
    "38": "Atkritumu savākšana, apstrāde un izvietošana",
    "39": "Sanācija un citi atkritumu apsaimniekošanas pakalpojumi",
    "41": "Ēku būvniecība",
    "42": "Inženierbūvniecība",
    "43": "Specializētie būvdarbi",
    "45": "Automobiļu un motociklu vairumtirdzniecība, mazumtirdzniecība un remonts",
    "46": "Vairumtirdzniecība, izņemot automobiļus un motociklus",
    "47": "Mazumtirdzniecība, izņemot automobiļus un motociklus",
    "49": "Sauszemes transports un cauruļvadu transports",
    "50": "Ūdens transports",
    "51": "Gaisa transports",
    "52": "Uzglabāšana un transporta palīgdarbības",
    "53": "Pasta un kurjeru darbība",
    "55": "Izmitināšana",
    "56": "Ēdināšanas pakalpojumi",
    "58": "Izdevējdarbība",
    "59": "Kinofilmu, video un televīzijas programmu producēšana",
    "60": "Programmu raidīšana",
    "61": "Elektronisko sakaru pakalpojumi",
    "62": "Datorprogrammēšana un konsultēšana",
    "63": "Informācijas pakalpojumi",
    "64": "Finanšu starpniecības pakalpojumi",
    "65": "Apdrošināšana un pensiju uzkrāšana",
    "66": "Finanšu un apdrošināšanas papildpakalpojumi",
    "68": "Operācijas ar nekustamo īpašumu",
    "69": "Juridiskās un grāmatvedības darbības",
    "70": "Galveno biroju darbība; konsultēšana komercdarbībā un vadībzinībās",
    "71": "Arhitektūras un inženiertehniskie pakalpojumi",
    "72": "Zinātniskā pētniecība un attīstība",
    "73": "Reklāmas un tirgus izpētes pakalpojumi",
    "74": "Citi profesionālie, zinātniskie un tehniskie pakalpojumi",
    "75": "Veterinārie pakalpojumi",
    "77": "Iznomāšana un ekspluatācijas līzings",
    "78": "Darbiekārtošanas pakalpojumi",
    "79": "Ceļojumu aģentūru un tūrisma operatoru pakalpojumi",
    "80": "Apsardzes un izmeklēšanas darbība",
    "81": "Ēku uzturēšana un ainavu veidošana",
    "82": "Biroja administratīvie un citi palīgpakalpojumi uzņēmumiem",
    "84": "Valsts pārvalde un aizsardzība; obligātā sociālā apdrošināšana",
    "85": "Izglītība",
    "86": "Veselības aizsardzība",
    "87": "Sociālā aprūpe ar izmitināšanu",
    "88": "Sociālā aprūpe bez izmitināšanas",
    "90": "Radošās, mākslas un izklaides darbības",
    "91": "Bibliotēku, arhīvu, muzeju un citu kultūras iestāžu darbība",
    "92": "Azartspēles un derības",
    "93": "Sporta, izklaides un atpūtas darbība",
    "94": "Biedrību darbība",
    "95": "Datoru, individuālās lietošanas priekšmetu un mājsaimniecības piederumu remonts",
    "96": "Citi individuālie pakalpojumi",
    "97": "Mājsaimniecības, kas nodarbina mājkalpotājus",
    "98": "Mājsaimniecību darbība pašu vajadzībām",
    "99": "Eksteritoriālu organizāciju un institūciju darbība",
}

# Fallback for codes not in dictionary
def get_nace_name(code: str) -> str:
    """Get NACE division name by 2-digit code"""
    return NACE_DIVISIONS.get(code, f"Nozare {code}")
